# Generated by Django 4.2.16 on 2024-12-06 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0006_patient_doctor"),
        (
            "staff_management",
            "0005_alter_employee_address_alter_employee_other1_and_more",
        ),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="test", max_length=100)),
                ("fees", models.CharField(max_length=5, null=True, unique=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[("Morning", "Morning"), ("Evening", "Evening")],
                        default="Morning",
                        max_length=50,
                    ),
                ),
                ("appointment_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("High", "High"),
                            ("Very High", "Very High"),
                            ("Low", "Low"),
                        ],
                        default="Normal",
                        max_length=50,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Transfer to Bank A/C", "Transfer to Bank A/C"),
                            ("UPI", "UPI"),
                            ("Card", "Card"),
                            ("Insurance", "Insurance"),
                        ],
                        default="Cash",
                        max_length=50,
                    ),
                ),
                (
                    "live_consult",
                    models.CharField(
                        choices=[("No", "No"), ("Yes", "Yes")],
                        default="No",
                        max_length=5,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff_management.employee",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
