# Generated by Django 4.2.16 on 2024-12-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("Consultation", "Consultation"),
                    ("Admission", "Admission"),
                    ("OPD", "OPD"),
                    ("IPD", "IPD"),
                    ("Appointment", "Appointment"),
                    ("Pharmacy", "Pharmacy"),
                    ("Pathology", "Pathology"),
                    ("Radiology", "Radiology"),
                    ("Operation", "Operation"),
                ],
                default="Consultation",
                max_length=50,
            ),
        ),
    ]
