# Generated by Django 4.2.16 on 2024-12-11 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff_management", "0008_alter_employee_user"),
        ("users", "0001_initial"),
        ("patients", "0007_alter_patient_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OPD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("symptoms", models.TextField(blank=True, null=True)),
                (
                    "charge_category",
                    models.CharField(
                        choices=[
                            ("OPD Consultation Fees", "OPD Consultation Fees"),
                            ("Blood Pressure Check", "Blood Pressure Check"),
                            ("Sugar Check", "Sugar Check"),
                            ("Other Charges", "Other Charges"),
                        ],
                        default="OPD Consultation Fees",
                        max_length=50,
                    ),
                ),
                ("charge", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Transfer to Bank A/C", "Transfer to Bank A/C"),
                            ("UPI", "UPI"),
                            ("Card", "Card"),
                            ("Insurance", "Insurance"),
                        ],
                        default="Cash",
                        max_length=50,
                    ),
                ),
                ("paid_amount", models.CharField(blank=True, max_length=50, null=True)),
                ("due_amount", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "live_consult",
                    models.CharField(
                        choices=[("No", "No"), ("Yes", "Yes")],
                        default="No",
                        max_length=5,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff_management.employee",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
