# Generated by Django 4.2.16 on 2024-12-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipd_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipdbill",
            name="qty",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
