# Generated by Django 4.2.16 on 2024-12-11 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0007_alter_patient_user"),
        ("staff_management", "0008_alter_employee_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiologyBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_no", models.CharField(blank=True, max_length=50, null=True)),
                ("test_name", models.CharField(blank=True, max_length=100, null=True)),
                ("report_time", models.CharField(blank=True, max_length=10, null=True)),
                ("amount", models.CharField(blank=True, max_length=10, null=True)),
                ("discount", models.CharField(blank=True, max_length=10, null=True)),
                ("tax", models.TextField(blank=True, null=True)),
                ("net_amount", models.TextField(blank=True, null=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Transfer to Bank A/C", "Transfer to Bank A/C"),
                            ("UPI", "UPI"),
                            ("Card", "Card"),
                            ("Insurance", "Insurance"),
                        ],
                        default="Cash",
                        max_length=50,
                    ),
                ),
                ("payment_amount", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff_management.employee",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Radiology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_type", models.CharField(blank=True, max_length=50, null=True)),
                ("test_name", models.CharField(blank=True, max_length=100, null=True)),
                ("category", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("method", models.CharField(blank=True, max_length=10, null=True)),
                ("report_time", models.CharField(blank=True, max_length=10, null=True)),
                ("charge_name", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "charge_amount",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("tax", models.TextField(blank=True, null=True)),
                ("total_amount", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
