# Generated by Django 4.2.16 on 2024-12-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiology_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radiology",
            name="tax",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="radiology",
            name="total_amount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
