# Generated by Django 4.2.16 on 2024-12-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="date_of_joining",
        ),
        migrations.AddField(
            model_name="employee",
            name="aadhar_back_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="aadhar_front_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="aadhar_no",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="account_holder_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="account_no",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="age",
            field=models.CharField(default="0", max_length=3),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="dob",
            field=models.DateField(default="2024-01-01"),
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="fees",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Not Specified", "Not Specified"),
                ],
                default="Not Specified",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="guardian_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="ifsc_code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_login",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_login_ip",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="latitude",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="location",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="longitude",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="notification_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="other1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="other2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="otp",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="otp_expire",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="pan_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="pan_no",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="plan_expire_date",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="plan_id",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="upi_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="zip",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
