# Generated by Django 4.2.16 on 2024-12-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0002_remove_employee_date_of_joining_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="age",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="guardian_name",
        ),
    ]
