# Generated by Django 4.2.16 on 2024-12-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0004_alter_employee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="other1",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="other2",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
