# Generated by Django 4.2.16 on 2024-12-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0006_alter_employee_email_alter_employee_user"),
        ("staff_management", "0006_alter_employee_user"),
    ]

    operations = []
