# Generated by Django 4.2.16 on 2024-12-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0008_alter_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="role",
            name="tenant",
        ),
    ]
