# Generated by Django 4.2.16 on 2024-12-18 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "staff_management",
            "0009_remove_employee_email_remove_employee_tenant_and_more",
        ),
        ("users", "0001_initial"),
        ("patients", "0007_alter_patient_user"),
        ("pharmacy_module", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicinelist",
            old_name="address",
            new_name="box_size",
        ),
        migrations.RenameField(
            model_name="medicinelist",
            old_name="registration_number",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="purchasemedicine",
            old_name="address",
            new_name="batch",
        ),
        migrations.RenameField(
            model_name="purchasemedicine",
            old_name="registration_number",
            new_name="batch_amount",
        ),
        migrations.RemoveField(
            model_name="medicinelist",
            name="name",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="address",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="name",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="registration_number",
        ),
        migrations.RemoveField(
            model_name="purchasemedicine",
            name="name",
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="bar_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="generic_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="manufacturer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="manufacturer_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="medicine_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="medicine_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="qty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="shelf",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="strength",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="tax",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="units",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="updated_at",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="amount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="bill_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="cost",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="discount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff_management.employee",
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="medicine_category",
            field=models.CharField(
                choices=[
                    ("Consultation Charges", "Consultation Charges"),
                    ("Pathology Charges", "Pathology Charges"),
                    ("Radiology Charges", "Radiology Charges"),
                    ("Misc.Charges", "Misc.Charges"),
                    ("Tablet", "Tablet"),
                    ("Syrup", "Syrup"),
                    ("Capsule", "Capsule"),
                    ("Injection", "Injection"),
                    ("Ointment", "Ointment"),
                    ("Cream", "Cream"),
                    ("Surgical", "Surgical"),
                    ("Drops", "Drops"),
                    ("Inhalers", "Inhalers"),
                    ("Implants / Patches", "Implants / Patches"),
                    ("Liquid", "Liquid"),
                    ("Preparations", "Preparations"),
                    ("Diaper", "Diaper"),
                ],
                default="Tablet",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="medicine_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pharmacy_module.medicinelist",
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="net_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="payment_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Transfer to Bank A/C", "Transfer to Bank A/C"),
                    ("UPI", "UPI"),
                    ("Card", "Card"),
                    ("Insurance", "Insurance"),
                ],
                default="Cash",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="qty",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="subtotal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="tax",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="tax_amount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="total_amount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="updated_at",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="discount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="expiry_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="manufacturer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="medicine_category",
            field=models.CharField(
                choices=[
                    ("Consultation Charges", "Consultation Charges"),
                    ("Pathology Charges", "Pathology Charges"),
                    ("Radiology Charges", "Radiology Charges"),
                    ("Misc.Charges", "Misc.Charges"),
                    ("Tablet", "Tablet"),
                    ("Syrup", "Syrup"),
                    ("Capsule", "Capsule"),
                    ("Injection", "Injection"),
                    ("Ointment", "Ointment"),
                    ("Cream", "Cream"),
                    ("Surgical", "Surgical"),
                    ("Drops", "Drops"),
                    ("Inhalers", "Inhalers"),
                    ("Implants / Patches", "Implants / Patches"),
                    ("Liquid", "Liquid"),
                    ("Preparations", "Preparations"),
                    ("Diaper", "Diaper"),
                ],
                default="Tablet",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="medicine_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pharmacy_module.medicinelist",
            ),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="mrp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="net_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="packing_qty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="payment_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Transfer to Bank A/C", "Transfer to Bank A/C"),
                    ("UPI", "UPI"),
                    ("Card", "Card"),
                    ("Insurance", "Insurance"),
                ],
                default="Cash",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="purchase_amount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="qty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="sale_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="subtotal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="tax",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="tax_amount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="total_amount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="updated_at",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
