# Generated by Django 4.2.16 on 2024-12-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.CharField(default="0", max_length=3),
        ),
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A+", "A+"),
                    ("B+", "B+"),
                    ("A-", "A-"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="A+",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="dapartment",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="dob",
            field=models.DateField(default="2024-01-01"),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Not Specified", "Not Specified"),
                ],
                default="Not Specified",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="guardian_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="identity_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Widowed", "Widowed"),
                    ("Separated", "Separated"),
                    ("Not Specified", "Not Specified"),
                ],
                default="Not Specified",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="tpa_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="tpa_validity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="zip",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(default="test", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
