# Generated by Django 4.2.16 on 2024-12-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_age_patient_allergies_patient_blood_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="dapartment",
            new_name="department",
        ),
    ]
