# Generated by Django 4.2.16 on 2024-12-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_rename_dapartment_patient_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="dob",
        ),
    ]
