# Generated by Django 4.2.16 on 2024-12-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_remove_patient_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="guardian_phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
