# Generated by Django 4.2.16 on 2024-12-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "staff_management",
            "0005_alter_employee_address_alter_employee_other1_and_more",
        ),
        ("patients", "0005_patient_guardian_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff_management.employee",
            ),
        ),
    ]
